### ISSUE TITLE
Unable to catch declared variable when it used in other statement (javascript)

### ISSUE THREAD

**Issue by inkz** [returntocorp/sgrep#195]
I try to catch this code example:
```javascript
var foo = "bar";
console.log(foo);
```

with this rule:
```yaml
rules:
 - id: test
   pattern: |
     var $X = ...;
     console.log($X);
   message: "test"
   languages: [javascript]
   severity: ERROR
```

and it returns 0 results :grimacing:

BUT it works if I try to catch lines separately
```bash
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop -e 'var $X = ...;' -l javascript .
```
```bash
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop -e 'console.log($X);' -l javascript .
```

trying to catch variable assignment instead of variable declaration works too
```javascript
var foo;
foo = "bar";
console.log(foo);
```
```yaml
rules:
 - id: test2
   pattern: |
     $X = ...;
     console.log($X);
   message: "test2"
   languages: [javascript]
   severity: ERROR
```
