### ISSUE TITLE
The 'patterns' and 'pattern-either' keys are not interchangeable as top-level patterns

### ISSUE THREAD

**Issue by mschwager** [returntocorp/sgrep#209]
Per the docs:

> * pattern-either: You can put multiple other patterns under this; any of those patterns will count as a match.
> * pattterns: Like pattern-either, you can put multiple patterns under this to create nested, implicitly-ANDed instructions.

This makes me think that both these options are interchangeable as an AND or OR operator. However, the following doesn't work for me:

Test file

```python
foo = {}
```

With `patterns`

```yaml
rules:
  - id: test-pattern
    patterns:
        - pattern: "$D = {}"
    message: "test"
    languages: [python]
    severity: WARNING
```

Gives:

```
running 1 rules from 1 yaml files (0 yaml files were invalid)

python/smells/manual-defaultdict-create.py
rule:test-pattern: test
1:foo = {}
```

With `pattern-either`

```yaml
rules:
  - id: test-pattern
    pattern-either:
        - pattern: "$D = {}"
    message: "test"
    languages: [python]
    severity: WARNING
```

Gives:

```
/home/repo/test.yaml has invalid rule key at rule 1 (rule id: test-pattern), can only have: {'id', 'pattern', 'patterns', 'message', 'severity', 'languages'}
running 0 rules from 0 yaml files (1 yaml files were invalid)
```
