### ISSUE TITLE
sgrep not working on js files

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#66]
See slack

**Comment by DrewDennison** [comment]
Steps to repro: 

1. clone https://github.com/inkz/test-sgrep-js
2. Try with sgrep itself
```
sgrep -e '$X == $X' -lang javascript .
Fatal error: exception (Failure "Find_source: unsupported language: javascript")
```
@aryx why is `javascript` not supported?
3. Run with `js`
```
sgrep -e '$X == $X' -lang js .
/Users/dennison/projects/test-sgrep-js/example.js:1
 if (1 == 1) {
```
4. Cat `.sgrep.yml`
```
cat .sgrep.yml
rules:
  - id: eqeq-is-bad
    pattern: $X == $X
    message: "Dude, $X == $X is always true!"
    languages: [js]
    severity: ERROR
```
5. run with verbose but no luck
```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:develop -v
DEBUG is on
running 1 rules from 1 yaml files (0 yaml files were invalid)
rules:
- id: '0.0'
  pattern: $X == $X
  severity: ERROR
  languages:
  - js
  message: <internalonly>

{"results": []}
sgrep ran in 0:00:00.140643
{'matches': [], 'errors': []}
```
cc @ievans for thoughts on why the `-rules-file` option doesn't seem to work with `js`
